package ProjectEuler;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import java.util.HashMap;

public class Problem2 {

    public static void main(String[] args){
        int n = 10;

        HashMap<Integer,Integer> memo = new HashMap<>();

        System.out.println(fibEvenSum(10,memo));

        //System.out.println(fibSum(4000000));

        //System.out.println(fibEvenSum(4000000));
    }

    public static int fib(int n) {
            if (n <= 1)
                return n;
            return fib(n-1) + fib(n-2);
    }


    public static int memoFib(int n ,HashMap<Integer,Integer> memo) {
        if(memo.containsKey(n)){
            return memo.get(n);
        }
        else{
            if (n <= 1){
                memo.put(n,n);
                return n;
            }
            memo.put(memoFib(n-1,memo) + memoFib(n-2,memo),memoFib(n-1,memo) + memoFib(n-2,memo));
            return memoFib(n-1,memo) + memoFib(n-2,memo);
        }
    }


    public static int fibSum(int n,HashMap<Integer,Integer> memo){
        int sum = 0;

        for(int i=0;i<n;i++){
            sum = sum + memoFib(i,memo);
        }
        return sum;
    }


    public static int fibEvenSum(int n,HashMap<Integer,Integer> memo){
        int evenSum = 0;
        for(int i=0;i<n;i++){
            if(memoFib(i,memo)%2==0) {
                int m = memoFib(i,memo);
                System.out.println(m);
                evenSum = evenSum + m;
            }
        }
        return evenSum;
    }



}
